version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}    
            - app-
      - run:
          name: Install dependencies
          command: npm install 
      - save_cache:
          key: app-{{ checksum "package.json" }}
          paths:
            - node_modules

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH} 
      - run:
          name: Installing awscli
          working_directory: /
          command: |    
            sudo apt-get update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
      - run:
          name: Deploy to AWS S3
          command: |
            aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_NAME} --delete --exact-timestamps
            echo "Deployment to AWS S3 Successful"